apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-nginx-leader-election
  labels:
    app.kubernetes.io/name: my-app-chart
    app.kubernetes.io/instance: my-app-chart
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch" ]
    resourceNames: [ "ingress-controller-leader" ]
