apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-nginx-leader-election-binding
  labels:
    app.kubernetes.io/name: my-app-chart
    app.kubernetes.io/instance: my-app-chart
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: ingress-nginx
    namespace: ingress-nginx
roleRef:
  kind: ClusterRole
  name: ingress-nginx-leader-election
  apiGroup: rbac.authorization.k8s.io
