apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-chart-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  labels:
    app.kubernetes.io/name: my-app-chart
    app.kubernetes.io/instance: my-app-chart
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-app-chart-service
                port:
                  number: 8080
